from pathlib import Path


DATA_DIR = Path("data/ml")
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
REPORT_DIR = DATA_DIR / "reports"

UNIVERSE_HISTORY_PATH = RAW_DIR / "universe_history.parquet"
PRICE_HISTORY_PATH = RAW_DIR / "price_history.parquet"
FLOW_HISTORY_PARQUET = RAW_DIR / "flow_history.parquet"
FUNDAMENTAL_HISTORY_PARQUET = RAW_DIR / "fundamental_history.parquet"
FEATURE_PANEL_PATH = PROCESSED_DIR / "feature_panel.parquet"
QUALITY_REPORT_PATH = REPORT_DIR / "data_quality.json"
MODEL_REPORT_PATH = REPORT_DIR / "model_report.json"
FEATURE_IMPORTANCE_PATH = REPORT_DIR / "feature_importance.csv"
OOS_PREDICTIONS_PATH = REPORT_DIR / "walk_forward_predictions.parquet"
TOP_SELECTION_PATH = REPORT_DIR / "top_selection.csv"

DEFAULT_START = "2018-01-01"
FINAL_DATASET_START = "2021-10-01"
MARKETS = ("KOSPI", "KOSDAQ")
TRAIN_UNIVERSE_SIZE_PER_MARKET = 100
PREDICTION_UNIVERSE_SIZE_PER_MARKET = 50
TOP_SELECTION_SIZE_PER_MARKET = 10
TRAIN_UNIVERSE_SIZE = TRAIN_UNIVERSE_SIZE_PER_MARKET * len(MARKETS)
PREDICTION_UNIVERSE_SIZE = PREDICTION_UNIVERSE_SIZE_PER_MARKET * len(MARKETS)
TOP_SELECTION_SIZE = TOP_SELECTION_SIZE_PER_MARKET * len(MARKETS)
PREDICTION_HORIZON = 10
EXCESS_RETURN_THRESHOLD = 0.03

RF_WEIGHT = 0.20
LGBM_CLASSIFIER_WEIGHT = 0.30
LGBM_RANKER_WEIGHT = 0.50
